version: '3.9'

services:

  docker-react-dev:
    container_name: docker-react-dev
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - '/app/node_modules'
      - '.:/app'
    ports:
      - "80:80"
      - "8080:80"
    